### PR TITLE
Add instructions for ruby 

### PR DESCRIPTION
**Pull request by postcumer**

### CODE REVIEW

**Review by gwolf2u — CHANGES_REQUESTED** [review]
should modify rubyx to ruby as that's not needed

**Comment by postcumer** [comment]
> should modify rubyx to ruby as that's not needed

You can see again there is no word rubyx neither ruby in installation instructions

**Comment by gwolf2u** [comment]
was referring to the file name
https://github.com/crdroidandroid/install_docs/blob/live/11/rubyx.md

**Comment by postcumer** [comment]
> was referring to the file name https://github.com/crdroidandroid/install_docs/blob/live/11/rubyx.md

Oh sure

**Comment by postcumer** [comment]
changes done

**Pull request merged**
